name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in root
      run: ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd browser/client
        npm install

    - name: Run tests
      run: |
        cd browser/client
        npm test

    - name: Build the project
      run: |
        cd browser/client
        npm run build